name: Run E2E Tests

on: [push]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - run: yarn --frozen-lockfile

      - run: yarn knex migrate:latest
        env:
          DATABASE_URL: "./db/test.db"
          NODE_ENV: test
          DATABASE_CLIENT: sqlite
          APP_SECRET: appsecret

      - run: yarn test
        env:
          DATABASE_URL: "./db/test.db"
          NODE_ENV: test
          DATABASE_CLIENT: sqlite
          APP_SECRET: appsecret